package org.firstinspires.ftc.teamcode.enums;


public enum AutonomousStates {
    START,
    LATCHED,
    DROPPED,
    MOVED_FORWARD,
    AT_MINERAL,
    AT_RIGHT_MINERAL,
    MINERAL_PUSHED,
    BACKED_AWAY_FROM_MINERAL,
    AT_DEPOT,
    DROPPED_MARKER,
    AT_LEFT_WALL,
    TURNED_TOWARDS_CRATER,
    AT_CRATER,
    ARM_EXTENDED,
    FACING_CRATER,
    MOVED_OFF_LATCH,
    MOVED_BACK_TO_CENTER,
    BACK_AT_MIDDLE,
    MINED,
    MINERAL_RIGHT_PUSHED,
    BACKED_AWAY_FROM_RIGHT_MINERAL,
    BACK_AT_CENTER,
    MINERALS_CENTER_LEFT,
    MINERAL_RIGHT,
    LIFT_DOWN,
    FLIP_DOWN,
    INTAKE_ON
}
